/* ============================== PASSIVE HELPERS ============================== */
export const FLAT = (stat, amount) => ({ kind: "flat", unlockStar: 1, stat, amount });
export const PCT = (stat, amount) => ({ kind: "percent", unlockStar: 3, stat, amount });
export const PERIODIC = (name, effect) => ({ kind: "periodic", unlockStar: 5, name, effect });
export const PROC = (name, effect) => ({ kind: "procSkill", unlockStar: 7, name, chance: 25, energyGain: 150, effect });

export const ROLE_COLOR = { Tank: "sky", Warrior: "rose", Assassin: "violet", Mage: "cyan", Ranger: "emerald", Support: "amber" };
export const RARITY_COLOR = { Common: "slate", Rare: "sky", Epic: "violet", Legendary: "amber" };
export const GRADE_COLOR = { 1: "slate", 2: "emerald", 3: "sky", 4: "violet", 5: "amber" };
export const GRADE_NAME = { 1: "Grade I", 2: "Grade II", 3: "Grade III", 4: "Grade IV", 5: "Grade V" };

export const HEROES = [
  { id: "kael", name: "Kael Ironwall", icon: "🛡️", role: "Tank", grade: 5, baseHp: 1440, baseAtk: 98, baseDef: 98, baseSpd: 86, energyMax: 500, ultimate: true,
    active: { name: "Bulwark Stand", desc: "Shields himself for 30% of his max HP.", target: "self", kind: "shield", pct: 30 },
    passives: [FLAT("def", 14), PCT("hp", 12), PERIODIC("Fortify", { target: "self", kind: "shield", pct: 10 }), PROC("Shield Bash", { target: "enemy", kind: "damage", mult: 75 })] },
  { id: "thrand", name: "Thrand Bastion", icon: "🪨", role: "Tank", grade: 3, baseHp: 1300, baseAtk: 80, baseDef: 90, baseSpd: 70, energyMax: 380, ultimate: false,
    active: { name: "Stonehide", desc: "The whole team gains +25% DEF for 3 turns.", target: "allAllies", kind: "buff", stat: "def", amount: 25, turns: 3 },
    passives: [FLAT("def", 18), PCT("hp", 10), PERIODIC("Aftershock", { target: "allEnemies", kind: "damage", mult: 25 }), PROC("Guard Slam", { target: "enemy", kind: "damage", mult: 80, ignoreDefPct: 20 })] },
  { id: "voss", name: "Voss the Unyielding", icon: "⛰️", role: "Tank", grade: 4, baseHp: 1150, baseAtk: 100, baseDef: 70, baseSpd: 85, energyMax: 420, ultimate: false,
    active: { name: "Retribution Slam", desc: "Slams the strongest enemy for 150% ATK and shields himself for 15% max HP.", target: "highestAtkEnemy", kind: "damage", mult: 150, selfShieldPct: 15 },
    passives: [FLAT("hp", 140), PCT("def", 12), PERIODIC("Grit", { target: "self", kind: "heal", pct: 8 }), PROC("Crushing Blow", { target: "highestAtkEnemy", kind: "damage", mult: 100 })] },
  { id: "mira", name: "Mira Duskblade", icon: "🌙", role: "Assassin", grade: 5, baseHp: 830, baseAtk: 178, baseDef: 37, baseSpd: 147, energyMax: 500, ultimate: true,
    active: { name: "Shadow Strike", desc: "Guaranteed critical strike on the lowest-HP enemy, anywhere in the formation, ignoring 30% DEF.", target: "anyLowestHpEnemy", kind: "damage", mult: 220, ignoreDefPct: 30, guaranteedCrit: true },
    passives: [FLAT("atk", 20), PCT("critChance", 16), PERIODIC("Blade Dance", { target: "self", kind: "buff", stat: "spd", amount: 10, turns: 2 }), PROC("Quick Cut", { target: "anyLowestHpEnemy", kind: "damage", mult: 90 })] },
  { id: "ryn", name: "Ryn Nightshiv", icon: "🐍", role: "Assassin", grade: 2, baseHp: 740, baseAtk: 145, baseDef: 35, baseSpd: 122, energyMax: 320, ultimate: false,
    active: { name: "Venom Flurry", desc: "Strikes 3 random enemies for 70% ATK each.", target: "randomEnemyX3", kind: "damage", mult: 70 },
    passives: [FLAT("spd", 6), PCT("critDamage", 20), PERIODIC("Venom Coat", { target: "self", kind: "buff", stat: "atk", amount: 8, turns: 2 }), PROC("Snakebite", { target: "anyLowestHpEnemy", kind: "damage", mult: 85 })] },
  { id: "sable", name: "Sable Fang", icon: "🦇", role: "Assassin", grade: 4, baseHp: 760, baseAtk: 150, baseDef: 38, baseSpd: 118, energyMax: 360, ultimate: false,
    active: { name: "Execution", desc: "Strikes the weakest foe anywhere for 160% ATK, +100% more if they're below 40% HP.", target: "anyLowestHpEnemy", kind: "damage", mult: 160, executeBonus: { threshold: 40, bonusPct: 100 } },
    passives: [FLAT("atk", 18), PCT("critChance", 12), PERIODIC("Predator's Patience", { target: "self", kind: "buff", stat: "atk", amount: 9, turns: 2 }), PROC("Gut Strike", { target: "anyLowestHpEnemy", kind: "damage", mult: 95, executeBonus: { threshold: 35, bonusPct: 40 } })] },
  { id: "garrick", name: "Garrick Stormbreaker", icon: "⚡", role: "Warrior", grade: 4, baseHp: 1090, baseAtk: 155, baseDef: 58, baseSpd: 115, energyMax: 500, ultimate: true,
    active: { name: "Thunderclap", desc: "Strikes all enemies for 90% ATK.", target: "allEnemies", kind: "damage", mult: 90 },
    passives: [FLAT("atk", 22), PCT("critDamage", 12), PERIODIC("Static Charge", { target: "self", kind: "buff", stat: "atk", amount: 10, turns: 2 }), PROC("Bolt Strike", { target: "enemy", kind: "damage", mult: 100, ignoreDefPct: 20 })] },
  { id: "dane", name: "Dane Bloodoath", icon: "🩸", role: "Warrior", grade: 2, baseHp: 1000, baseAtk: 125, baseDef: 55, baseSpd: 90, energyMax: 400, ultimate: false,
    active: { name: "Bloodletting", desc: "Strikes for 180% ATK and heals for 50% of the damage dealt.", target: "enemy", kind: "damage", mult: 180, selfHealPctOfDamageDealt: 50 },
    passives: [FLAT("hp", 130), PCT("atk", 10), PERIODIC("Bloodscent", { target: "self", kind: "heal", pct: 6 }), PROC("Savage Bite", { target: "enemy", kind: "damage", mult: 90, selfHealPctOfDamageDealt: 30 })] },
  { id: "orin", name: "Orin Steelheart", icon: "⚔️", role: "Warrior", grade: 1, baseHp: 980, baseAtk: 120, baseDef: 60, baseSpd: 92, energyMax: 340, ultimate: false,
    active: { name: "Rally Cry", desc: "The whole team gains +20% ATK for 3 turns.", target: "allAllies", kind: "buff", stat: "atk", amount: 20, turns: 3 },
    passives: [FLAT("atk", 16), PCT("def", 10), PERIODIC("Battle Hymn", { target: "allAllies", kind: "buff", stat: "atk", amount: 8, turns: 2 }), PROC("Iron Cleave", { target: "allEnemies", kind: "damage", mult: 45 })] },
  { id: "brogan", name: "Brogan Doomhorn", icon: "🐂", role: "Warrior", grade: 1, baseHp: 1050, baseAtk: 128, baseDef: 58, baseSpd: 88, energyMax: 470, ultimate: false,
    active: { name: "Doom Charge", desc: "Gores a foe for 200% ATK and gains +15% ATK for 2 turns.", target: "enemy", kind: "damage", mult: 200, selfBuff: { stat: "atk", amount: 15, turns: 2 } },
    passives: [FLAT("hp", 160), PCT("atk", 9), PERIODIC("Rage Building", { target: "self", kind: "buff", stat: "atk", amount: 12, turns: 2 }), PROC("Skullcrack", { target: "enemy", kind: "damage", mult: 100, stunChance: 15 })] },
  { id: "lyanna", name: "Lyanna Frostweave", icon: "❄️", role: "Mage", grade: 3, baseHp: 700, baseAtk: 145, baseDef: 28, baseSpd: 104, energyMax: 460, ultimate: false,
    active: { name: "Glacial Nova", desc: "Blasts all enemies for 80% ATK, each with a 30% chance to freeze for a turn.", target: "allEnemies", kind: "damage", mult: 80, stunChance: 30 },
    passives: [FLAT("atk", 18), PCT("critDamage", 16), PERIODIC("Frost Focus", { target: "self", kind: "buff", stat: "atk", amount: 8, turns: 2 }), PROC("Ice Shard", { target: "enemy", kind: "damage", mult: 90, stunChance: 15 })] },
  { id: "zerin", name: "Zerin Emberhand", icon: "🔥", role: "Mage", grade: 5, baseHp: 780, baseAtk: 178, baseDef: 35, baseSpd: 115, energyMax: 500, ultimate: true,
    active: { name: "Emberstorm", desc: "Engulfs a single enemy in fire for 250% ATK.", target: "enemy", kind: "damage", mult: 250 },
    passives: [FLAT("atk", 24), PCT("critChance", 14), PERIODIC("Ember Focus", { target: "self", kind: "buff", stat: "atk", amount: 10, turns: 2 }), PROC("Flame Lash", { target: "enemy", kind: "damage", mult: 95 })] },
  { id: "nox", name: "Nox Voidcaller", icon: "🌑", role: "Mage", grade: 2, baseHp: 720, baseAtk: 140, baseDef: 32, baseSpd: 98, energyMax: 390, ultimate: false,
    active: { name: "Entropy Field", desc: "Corrodes all enemies for 40% ATK and cuts their DEF by 20% for 3 turns.", target: "allEnemies", kind: "damage", mult: 40, andDebuff: { stat: "def", amount: 20, turns: 3 } },
    passives: [FLAT("atk", 16), PCT("critChance", 9), PERIODIC("Void Whisper", { target: "allEnemies", kind: "debuff", stat: "def", amount: 8, turns: 2 }), PROC("Void Bolt", { target: "enemy", kind: "damage", mult: 90 })] },
  { id: "wren", name: "Wren Hawkeye", icon: "🦅", role: "Ranger", grade: 3, baseHp: 800, baseAtk: 130, baseDef: 38, baseSpd: 115, energyMax: 350, ultimate: false,
    active: { name: "Piercing Shot", desc: "Fires an armor-piercing shot for 200% ATK, ignoring 50% DEF.", target: "enemy", kind: "damage", mult: 200, ignoreDefPct: 50 },
    passives: [FLAT("spd", 7), PCT("critChance", 14), PERIODIC("Eagle Focus", { target: "self", kind: "buff", stat: "atk", amount: 9, turns: 2 }), PROC("Snap Shot", { target: "enemy", kind: "damage", mult: 90 })] },
  { id: "tessa", name: "Tessa Swiftarrow", icon: "🏹", role: "Ranger", grade: 2, baseHp: 780, baseAtk: 125, baseDef: 40, baseSpd: 118, energyMax: 300, ultimate: false,
    active: { name: "Rain of Arrows", desc: "Peppers all enemies for 60% ATK.", target: "allEnemies", kind: "damage", mult: 60 },
    passives: [FLAT("spd", 9), PCT("critDamage", 12), PERIODIC("Fleet Step", { target: "self", kind: "buff", stat: "spd", amount: 10, turns: 2 }), PROC("Double Tap", { target: "enemy", kind: "damage", mult: 90 })] },
  { id: "kade", name: "Kade Longshot", icon: "🎯", role: "Ranger", grade: 4, baseHp: 910, baseAtk: 155, baseDef: 41, baseSpd: 127, energyMax: 500, ultimate: true,
    active: { name: "Deadeye", desc: "A guaranteed critical hit on a single enemy for 180% ATK.", target: "enemy", kind: "damage", mult: 180, guaranteedCrit: true },
    passives: [FLAT("atk", 18), PCT("critChance", 18), PERIODIC("Steady Aim", { target: "self", kind: "buff", stat: "atk", amount: 10, turns: 2 }), PROC("Called Shot", { target: "enemy", kind: "damage", mult: 100, guaranteedCrit: true })] },
  { id: "elara", name: "Elara Dawnsong", icon: "🌅", role: "Support", grade: 5, baseHp: 980, baseAtk: 86, baseDef: 52, baseSpd: 117, energyMax: 500, ultimate: true,
    active: { name: "Dawn's Grace", desc: "Heals the whole team for 25% of their max HP.", target: "allAllies", kind: "heal", pct: 25 },
    passives: [FLAT("hp", 150), PCT("def", 8), PERIODIC("Gentle Light", { target: "lowestHpAlly", kind: "heal", pct: 8 }), PROC("Radiant Pulse", { target: "allAllies", kind: "heal", pct: 10 })] },
  { id: "petra", name: "Petra Lifebloom", icon: "🌿", role: "Support", grade: 3, baseHp: 880, baseAtk: 70, baseDef: 50, baseSpd: 98, energyMax: 430, ultimate: false,
    active: { name: "Blooming Ward", desc: "Shields the lowest-HP ally for 40% max HP and heals them 15%.", target: "lowestHpAlly", kind: "shield", pct: 40, andHealPct: 15 },
    passives: [FLAT("hp", 160), PCT("def", 9), PERIODIC("Bloom", { target: "lowestHpAlly", kind: "heal", pct: 7 }), PROC("Vine Guard", { target: "lowestHpAlly", kind: "shield", pct: 12 })] },
  { id: "ansel", name: "Ansel Warden", icon: "🕊️", role: "Support", grade: 2, baseHp: 900, baseAtk: 72, baseDef: 55, baseSpd: 95, energyMax: 440, ultimate: false,
    active: { name: "Cleansing Light", desc: "Cleanses all debuffs from the team and heals them 10%.", target: "allAllies", kind: "cleanse", andHealPct: 10 },
    passives: [FLAT("def", 16), PCT("hp", 10), PERIODIC("Ward", { target: "allAllies", kind: "buff", stat: "def", amount: 6, turns: 2 }), PROC("Aegis Light", { target: "lowestHpAlly", kind: "shield", pct: 15 })] },
  { id: "yusra", name: "Yusra Chronomancer", icon: "⏳", role: "Support", grade: 3, baseHp: 800, baseAtk: 90, baseDef: 40, baseSpd: 108, energyMax: 410, ultimate: false,
    active: { name: "Time Skip", desc: "Fills an ally's energy to full and grants +30% SPD for 2 turns.", target: "highestAtkAlly", kind: "energyFull", amount: 30, turns: 2 },
    passives: [FLAT("spd", 8), PCT("hp", 8), PERIODIC("Time Sense", { target: "self", kind: "buff", stat: "spd", amount: 10, turns: 2 }), PROC("Haste Pulse", { target: "allAllies", kind: "buff", stat: "spd", amount: 8, turns: 2 })] },
  { id: "borin", name: "Borin Deepshield", icon: "🗿", role: "Tank", grade: 3, baseHp: 1280, baseAtk: 88, baseDef: 88, baseSpd: 78, energyMax: 400, ultimate: false,
    active: { name: "Bulwark Line", desc: "The whole team gains +20% DEF for 3 turns.", target: "allAllies", kind: "buff", stat: "def", amount: 20, turns: 3 },
    passives: [FLAT("def", 15), PCT("hp", 11), PERIODIC("Deep Roots", { target: "self", kind: "buff", stat: "def", amount: 15, turns: 2 }), PROC("Earthshatter", { target: "allEnemies", kind: "damage", mult: 35 })] },
  { id: "vasha", name: "Vasha Stoneheart", icon: "🏔️", role: "Tank", grade: 5, baseHp: 1414, baseAtk: 105, baseDef: 100, baseSpd: 90, energyMax: 500, ultimate: true,
    active: { name: "Mountain's Judgment", desc: "Smashes all enemies for 70% ATK and cuts their ATK by 15% for 3 turns.", target: "allEnemies", kind: "damage", mult: 70, andDebuff: { stat: "atk", amount: 15, turns: 3 } },
    passives: [FLAT("hp", 150), PCT("def", 13), PERIODIC("Stone Skin", { target: "self", kind: "shield", pct: 12 }), PROC("Avalanche", { target: "enemy", kind: "damage", mult: 110, executeBonus: { threshold: 30, bonusPct: 60 } })] },
  { id: "grimjaw", name: "Grimjaw the Wall", icon: "🧱", role: "Tank", grade: 1, baseHp: 1350, baseAtk: 78, baseDef: 95, baseSpd: 68, energyMax: 360, ultimate: false,
    active: { name: "Immovable", desc: "Shields himself for 40% of his max HP.", target: "self", kind: "shield", pct: 40 },
    passives: [FLAT("def", 20), PCT("hp", 9), PERIODIC("Wall Up", { target: "self", kind: "buff", stat: "def", amount: 20, turns: 2 }), PROC("Haymaker", { target: "enemy", kind: "damage", mult: 90, stunChance: 20 })] },
  { id: "kestrel", name: "Kestrel Ashblade", icon: "🔱", role: "Warrior", grade: 3, baseHp: 1000, baseAtk: 138, baseDef: 56, baseSpd: 102, energyMax: 430, ultimate: false,
    active: { name: "Ashen Cyclone", desc: "Spins through all enemies for 85% ATK.", target: "allEnemies", kind: "damage", mult: 85 },
    passives: [FLAT("atk", 20), PCT("critDamage", 13), PERIODIC("Ashen Edge", { target: "self", kind: "buff", stat: "atk", amount: 10, turns: 2 }), PROC("Rending Slash", { target: "enemy", kind: "damage", mult: 95, ignoreDefPct: 25 })] },
  { id: "draven", name: "Draven Ironfist", icon: "👊", role: "Warrior", grade: 2, baseHp: 1020, baseAtk: 122, baseDef: 58, baseSpd: 93, energyMax: 370, ultimate: false,
    active: { name: "Iron Fist Combo", desc: "A relentless combo for 190% ATK, ignoring 25% DEF.", target: "enemy", kind: "damage", mult: 190, ignoreDefPct: 25 },
    passives: [FLAT("atk", 17), PCT("def", 9), PERIODIC("Iron Focus", { target: "self", kind: "shield", pct: 8 }), PROC("Haymaker Combo", { target: "enemy", kind: "damage", mult: 85, andDebuff: { stat: "def", amount: 10, turns: 2 } })] },
  { id: "sorka", name: "Sorka Warcry", icon: "📯", role: "Warrior", grade: 1, baseHp: 960, baseAtk: 118, baseDef: 52, baseSpd: 97, energyMax: 460, ultimate: false,
    active: { name: "Warcry", desc: "The whole team gains +18% ATK for 3 turns.", target: "allAllies", kind: "buff", stat: "atk", amount: 18, turns: 3 },
    passives: [FLAT("atk", 15), PCT("spd", 8), PERIODIC("War Drums", { target: "allAllies", kind: "buff", stat: "spd", amount: 8, turns: 2 }), PROC("Warcry Slam", { target: "allEnemies", kind: "damage", mult: 40 })] },
  { id: "vex", name: "Vex Shadowstep", icon: "🕷️", role: "Assassin", grade: 2, baseHp: 750, baseAtk: 148, baseDef: 34, baseSpd: 125, energyMax: 330, ultimate: false,
    active: { name: "Vanish Strike", desc: "A guaranteed critical strike on the weakest enemy for 210% ATK.", target: "anyLowestHpEnemy", kind: "damage", mult: 210, guaranteedCrit: true },
    passives: [FLAT("spd", 6), PCT("dodge", 10), PERIODIC("Fade Step", { target: "self", kind: "shield", pct: 6 }), PROC("Backstab", { target: "anyLowestHpEnemy", kind: "damage", mult: 100, ignoreDefPct: 20 })] },
  { id: "nyx", name: "Nyx Silentknife", icon: "🗡️", role: "Assassin", grade: 3, baseHp: 730, baseAtk: 152, baseDef: 33, baseSpd: 130, energyMax: 310, ultimate: false,
    active: { name: "Silent Kill", desc: "Strikes the weakest foe anywhere for 170% ATK, +80% more if they're below 35% HP.", target: "anyLowestHpEnemy", kind: "damage", mult: 170, executeBonus: { threshold: 35, bonusPct: 80 } },
    passives: [FLAT("spd", 7), PCT("critChance", 15), PERIODIC("Silent Focus", { target: "self", kind: "buff", stat: "spd", amount: 9, turns: 2 }), PROC("Silent Strike", { target: "anyLowestHpEnemy", kind: "damage", mult: 90, guaranteedCrit: true })] },
  { id: "corvin", name: "Corvin Nightowl", icon: "🦉", role: "Assassin", grade: 4, baseHp: 770, baseAtk: 155, baseDef: 36, baseSpd: 120, energyMax: 450, ultimate: false,
    active: { name: "Talon Storm", desc: "Strikes 3 random enemies for 75% ATK each.", target: "randomEnemyX3", kind: "damage", mult: 75 },
    passives: [FLAT("atk", 19), PCT("critChance", 13), PERIODIC("Night Vision", { target: "self", kind: "buff", stat: "atk", amount: 10, turns: 2 }), PROC("Talon Rake", { target: "anyLowestHpEnemy", kind: "damage", mult: 95 })] },
  { id: "ignis", name: "Ignis Pyroclast", icon: "🌋", role: "Mage", grade: 4, baseHp: 700, baseAtk: 160, baseDef: 30, baseSpd: 105, energyMax: 480, ultimate: false,
    active: { name: "Volcanic Eruption", desc: "Erupts beneath all enemies for 95% ATK.", target: "allEnemies", kind: "damage", mult: 95 },
    passives: [FLAT("atk", 20), PCT("critDamage", 15), PERIODIC("Smolder", { target: "allEnemies", kind: "damage", mult: 15 }), PROC("Magma Burst", { target: "allEnemies", kind: "damage", mult: 30 })] },
  { id: "selene", name: "Selene Moonveil", icon: "🌕", role: "Mage", grade: 2, baseHp: 710, baseAtk: 142, baseDef: 31, baseSpd: 100, energyMax: 340, ultimate: false,
    active: { name: "Lunar Cascade", desc: "Bathes a single enemy in moonlight for 230% ATK.", target: "enemy", kind: "damage", mult: 230 },
    passives: [FLAT("atk", 15), PCT("hp", 9), PERIODIC("Lunar Grace", { target: "self", kind: "heal", pct: 7 }), PROC("Moonbeam", { target: "enemy", kind: "damage", mult: 100 })] },
  { id: "thessaly", name: "Thessaly Stormcaller", icon: "⛈️", role: "Mage", grade: 5, baseHp: 790, baseAtk: 179, baseDef: 36, baseSpd: 118, energyMax: 500, ultimate: true,
    active: { name: "Tempest Call", desc: "Calls a storm on all enemies for 85% ATK, each with a 25% chance to freeze.", target: "allEnemies", kind: "damage", mult: 85, stunChance: 25 },
    passives: [FLAT("atk", 22), PCT("spd", 9), PERIODIC("Static Field", { target: "self", kind: "buff", stat: "spd", amount: 10, turns: 2 }), PROC("Lightning Rod", { target: "enemy", kind: "damage", mult: 105, andDebuff: { stat: "def", amount: 15, turns: 2 } })] },
  { id: "malachar", name: "Malachar the Cursed", icon: "💀", role: "Mage", grade: 4, baseHp: 740, baseAtk: 148, baseDef: 30, baseSpd: 96, energyMax: 420, ultimate: false,
    active: { name: "Soul Drain", desc: "Drains a foe for 200% ATK, healing for 40% of the damage dealt.", target: "enemy", kind: "damage", mult: 200, selfHealPctOfDamageDealt: 40 },
    passives: [FLAT("atk", 17), PCT("critChance", 11), PERIODIC("Cursed Whisper", { target: "anyLowestHpEnemy", kind: "debuff", stat: "atk", amount: 10, turns: 2 }), PROC("Dark Pact", { target: "enemy", kind: "damage", mult: 100, selfHealPctOfDamageDealt: 20 })] },
  { id: "fen", name: "Fen Thistlebow", icon: "🌾", role: "Ranger", grade: 1, baseHp: 800, baseAtk: 128, baseDef: 39, baseSpd: 112, energyMax: 305, ultimate: false,
    active: { name: "Bramble Volley", desc: "Fires thorned arrows at all enemies for 65% ATK, cutting DEF 15% for 3 turns.", target: "allEnemies", kind: "damage", mult: 65, andDebuff: { stat: "def", amount: 15, turns: 3 } },
    passives: [FLAT("spd", 6), PCT("dodge", 8), PERIODIC("Thicket Cover", { target: "self", kind: "shield", pct: 7 }), PROC("Thistle Shot", { target: "enemy", kind: "damage", mult: 85, andDebuff: { stat: "def", amount: 10, turns: 2 } })] },
  { id: "skye", name: "Skye Windrider", icon: "🌬️", role: "Ranger", grade: 2, baseHp: 790, baseAtk: 132, baseDef: 37, baseSpd: 120, energyMax: 355, ultimate: false,
    active: { name: "Wind Barrage", desc: "A piercing barrage for 195% ATK, ignoring 40% DEF.", target: "enemy", kind: "damage", mult: 195, ignoreDefPct: 40 },
    passives: [FLAT("spd", 8), PCT("critDamage", 10), PERIODIC("Tailwind", { target: "self", kind: "buff", stat: "spd", amount: 12, turns: 2 }), PROC("Gale Arrow", { target: "enemy", kind: "damage", mult: 90 })] },
  { id: "orik", name: "Orik Trapmaster", icon: "🪤", role: "Ranger", grade: 1, baseHp: 810, baseAtk: 126, baseDef: 40, baseSpd: 108, energyMax: 395, ultimate: false,
    active: { name: "Trap Snare", desc: "Snares a foe for 150% ATK with a 40% chance to freeze them.", target: "enemy", kind: "damage", mult: 150, stunChance: 40 },
    passives: [FLAT("atk", 14), PCT("def", 8), PERIODIC("Trap Set", { target: "highestAtkEnemy", kind: "debuff", stat: "def", amount: 12, turns: 2 }), PROC("Snare Shot", { target: "enemy", kind: "damage", mult: 85, stunChance: 20 })] },
  { id: "lira", name: "Lira Snowtracker", icon: "🦌", role: "Ranger", grade: 3, baseHp: 800, baseAtk: 130, baseDef: 38, baseSpd: 116, energyMax: 415, ultimate: false,
    active: { name: "Frozen Volley", desc: "Chills all enemies for 70% ATK, each with a 20% chance to freeze.", target: "allEnemies", kind: "damage", mult: 70, stunChance: 20 },
    passives: [FLAT("spd", 7), PCT("critChance", 12), PERIODIC("Cold Trail", { target: "self", kind: "buff", stat: "atk", amount: 8, turns: 2 }), PROC("Frost Arrow", { target: "enemy", kind: "damage", mult: 90, stunChance: 15 })] },
  { id: "faye", name: "Faye Lightweaver", icon: "🕯️", role: "Support", grade: 3, baseHp: 870, baseAtk: 76, baseDef: 48, baseSpd: 100, energyMax: 445, ultimate: false,
    active: { name: "Beacon of Hope", desc: "Heals the whole team for 22% of their max HP.", target: "allAllies", kind: "heal", pct: 22 },
    passives: [FLAT("hp", 120), PCT("def", 7), PERIODIC("Soft Glow", { target: "lowestHpAlly", kind: "heal", pct: 8 }), PROC("Light Mend", { target: "allAllies", kind: "heal", pct: 8 })] },
  { id: "bram", name: "Bram Stonewarden", icon: "🧿", role: "Support", grade: 2, baseHp: 910, baseAtk: 74, baseDef: 56, baseSpd: 94, energyMax: 385, ultimate: false,
    active: { name: "Guardian Wall", desc: "Shields the lowest-HP ally for 45% max HP and heals them 10%.", target: "lowestHpAlly", kind: "shield", pct: 45, andHealPct: 10 },
    passives: [FLAT("def", 17), PCT("hp", 9), PERIODIC("Steady Ward", { target: "allAllies", kind: "buff", stat: "def", amount: 7, turns: 2 }), PROC("Bastion Light", { target: "lowestHpAlly", kind: "shield", pct: 14 })] },
  { id: "odalys", name: "Odalys Soulmender", icon: "💫", role: "Support", grade: 4, baseHp: 850, baseAtk: 82, baseDef: 45, baseSpd: 106, energyMax: 470, ultimate: false,
    active: { name: "Soul Weave", desc: "Cleanses all debuffs from the team and heals them 12%.", target: "allAllies", kind: "cleanse", andHealPct: 12 },
    passives: [FLAT("hp", 130), PCT("spd", 7), PERIODIC("Soul Thread", { target: "lowestHpAlly", kind: "heal", pct: 9 }), PROC("Soul Surge", { target: "lowestHpAlly", kind: "shield", pct: 12, andHealPct: 8 })] },
];

export const HEROES_BY_ID = Object.fromEntries(HEROES.map((h) => [h.id, h]));
